export const products = [
  {
    "slug": "sibjangsaeng-cheonsim-toner",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 천심수",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-toner.png",
    "summary": "천심 토너는 자극 없이 가볍게 스며드는 질감으로 피부 속 수분을 빠르게 공급합니다.",
    "description": "천심 토너는 자극 없이 가볍게 스며드는 질감으로 피부 속 수분을 빠르게 공급합니다. 한방 추출 성분이 피부 표면을 촉촉하게 정돈해 건조함과 당김을 줄여주며, 다음 단계 제품이 더 잘 흡수될 수 있도록 피부 환경을 만들어 줍니다.\n\n용량 및 구성: 150ml ㅣ 55,000원\n\n라인: Cheonshim Toner"
  },
  {
    "slug": "sibjangsaeng-cheonsim-emulsion",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 천심액",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-emulsion.png",
    "summary": "천심액은 가볍고 촉촉한 질감으로 피부 속 수분과 영양을 빠르게 공급합니다.",
    "description": "천심액은 가볍고 촉촉한 질감으로 피부 속 수분과 영양을 빠르게 공급합니다. 한방 추출 성분이 피부 표면을 부드럽게 정돈해 건조함과 당김을 줄여주며, 피부 보호막을 형성해 수분이 날아가지 않도록 잡아줍니다.\n\n용량 및 구성: 150ml ㅣ 55,000원\n\n라인: Cheonshim Emulsion"
  },
  {
    "slug": "sibjangsaeng-cheonsim-essence",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천심 자양 에센스",
    "price": "110,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-essence.png",
    "summary": "천심 자양에센스는 고농축 한방 추출 성분이 피부 속 깊이 빠르게 흡수되어 집중적인 자양과 영양을 공급합니다.",
    "description": "천심 자양에센스는 고농축 한방 추출 성분이 피부 속 깊이 빠르게 흡수되어 집중적인 자양과 영양을 공급합니다. 피부 본연의 생기와 탄력을 끌어올려 칙칙함과 건조함을 개선하며, 다음 단계 제품의 효과를 극대화할 수 있도록 피부 결을 정돈해 줍니다.\n\n용량 및 구성: 45ml ㅣ 110,000원 ㅣ Ampoule 10ml\n\n라인: Cheonshim Essence"
  },
  {
    "slug": "sibjangsaeng-cheonsim-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천심 자양크림",
    "price": "110,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-cream.png",
    "summary": "천심 크림은 발효 한방 추출 성분이 피부 깊은 곳에서부터 장벽을 단단히 다져줍니다.",
    "description": "천심 크림은 발효 한방 추출 성분이 피부 깊은 곳에서부터 장벽을 단단히 다져줍니다. 피부 본연의 탄력과 윤기를 끌어올려 거칠고 푸석한 피부결을 개선하며, 하루의 스킨케어를 풍성하게 마무리해 줍니다.\n\n용량 및 구성: 50ml ㅣ 110,000원 ㅣ Ampoule 10ml\n\n라인: Cheonshim Cream"
  },
  {
    "slug": "sibjangsaeng-cheonsim-eye-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천심 아이크림",
    "price": "110,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-eye-cream.png",
    "summary": "천심 아이크림은 발효 한방 추출 성분이 눈가의 얇고 예민한 피부 깊이 빠르게 스며들어 집중적인 영양을 공급합니다.",
    "description": "천심 아이크림은 발효 한방 추출 성분이 눈가의 얇고 예민한 피부 깊이 빠르게 스며들어 집중적인 영양을 공급합니다. 잔주름과 건조함을 개선하고 처진 눈가에 탄력과 생기를 더해 또렷하고 건강한 눈매로 가꾸어 줍니다.\n\n용량 및 구성: 50ml ㅣ 110,000원 ㅣ Ampoule 10ml\n\n라인: Cheonshim Eye Cream"
  },
  {
    "slug": "sibjangsaeng-cheonsim-2set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 천심 2종 세트",
    "price": "110,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-2set.png",
    "summary": "천심수와 천심액, 천심 아이크림으로 구성된 피부관리 루틴. 피부 속 깊이 수분을 채우고 아이크림으로 단단히 마무리하여, 맑고 건강한 피부결을 보다 효과적으로 이끌어 줍니다.",
    "description": "천심수와 천심액, 천심 아이크림으로 구성된 피부관리 루틴. 피부 속 깊이 수분을 채우고 아이크림으로 단단히 마무리하여, 맑고 건강한 피부결을 보다 효과적으로 이끌어 줍니다.\n\n용량 및 구성: 150ml + 150ml ㅣ 110,000원 ㅣ Eyecream 30ml\n\n라인: Cheonshim 2-Set"
  },
  {
    "slug": "sibjangsaeng-cheonsim-sun-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "십장생 천심 썬크림",
    "price": "40,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsim-sun-cream.png",
    "summary": "천심 썬크림은 발효 한방 추출 성분이 자외선 차단과 동시에 피부 결을 부드럽게 정돈해 줍니다.",
    "description": "천심 썬크림은 발효 한방 추출 성분이 자외선 차단과 동시에 피부 결을 부드럽게 정돈해 줍니다. 외부 자극으로부터 피부를 보호하면서도 산뜻하고 가볍게 마무리되어 일상의 마지막 한방 케어로 완성됩니다.\n\n용량 및 구성: 80ml ㅣ 40,000원 ㅣ Foam Cleanser 50ml\n\n라인: Cheonshim Sun Cream SPF50+ PA+++"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-toner",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 천지향 수액",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-toner.png",
    "summary": "천지향 수액은 산삼배양근 성분을 담아 손상된 피부를 재생하고 수분을 공급합니다.",
    "description": "천지향 수액은 산삼배양근 성분을 담아 손상된 피부를 재생하고 수분을 공급합니다. 피부결을 매끄럽게 정돈하며 이후 단계의 흡수를 돕는 스킨케어의 첫 걸음입니다.\n\n용량 및 구성: 150ml ㅣ 60,000원\n\n라인: Cheonjiyang Skin Toner"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-emulsion",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 천지향 유액",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-emulsion.png",
    "summary": "천지향 유액은 한방 발효 추출 성분이 피부 속 수분막을 형성하여 촉촉함을 오래 유지시켜 줍니다.",
    "description": "천지향 유액은 한방 발효 추출 성분이 피부 속 수분막을 형성하여 촉촉함을 오래 유지시켜 줍니다. 가볍고 산뜻하게 흡수되며 수분과 유분의 밸런스를 균형 있게 케어합니다.\n\n용량 및 구성: 150ml ㅣ 60,000원\n\n라인: Cheonjiyang Emulsion"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-essence",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천지향진액",
    "price": "130,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-essence.png",
    "summary": "천지향진액은 야생 산삼 배양 성분을 고농축으로 담아 피부 탄력과 윤기를 집중적으로 케어합니다.",
    "description": "천지향진액은 야생 산삼 배양 성분을 고농축으로 담아 피부 탄력과 윤기를 집중적으로 케어합니다. 바르는 즉시 피부 깊은 층까지 흡수되어 생기 있는 피부결로 가꾸어 줍니다.\n\n용량 및 구성: 45ml ㅣ 130,000원 ㅣ toner, emulsion 31ml / cream 15ml\n\n라인: Cheonjiyang Essence"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천지향 크림",
    "price": "130,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-cream.png",
    "summary": "천지향 크림은 한방 유효 성분이 피부 깊은 곳에서 영양을 집중 공급하고 탄탄한 장벽을 형성합니다.",
    "description": "천지향 크림은 한방 유효 성분이 피부 깊은 곳에서 영양을 집중 공급하고 탄탄한 장벽을 형성합니다. 건조하고 푸석한 피부를 윤기 있게 가꾸며 스킨케어 마지막 단계를 풍성하게 마무리해 줍니다.\n\n용량 및 구성: 50ml ㅣ 130,000원 ㅣ toner, emulsion 31ml / ampoule 10ml\n\n라인: Cheonjiyang Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-eye-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천지향 아이크림",
    "price": "130,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-eye-cream.png",
    "summary": "천지향 아이크림은 섬세한 눈가 피부에 집중적으로 영양을 전달합니다.",
    "description": "천지향 아이크림은 섬세한 눈가 피부에 집중적으로 영양을 전달합니다. 잔주름과 처짐을 개선하고 눈가를 환하고 탄탄하게 정돈해 주는 눈가 전용 크림입니다.\n\n용량 및 구성: 50ml ㅣ 130,000원 ㅣ toner, emulsion 31ml\n\n라인: Cheonjiyang Eye Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-massage-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "십장생 천지향 마사지 크림",
    "price": "42,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-massage-cream.png",
    "summary": "천지향 마사지 크림은 한방 성분의 풍부한 영양을 담아 마사지하는 동안 피부 순환을 촉진시킵니다.",
    "description": "천지향 마사지 크림은 한방 성분의 풍부한 영양을 담아 마사지하는 동안 피부 순환을 촉진시킵니다. 긴장된 피부를 이완시키고 광채 나는 탄력 피부로 가꾸어 줍니다.\n\n용량 및 구성: 250ml ㅣ 42,000원\n\n라인: Cheonjiyang Massage Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-cleansing-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "십장생 천지향 클렌징 크림",
    "price": "35,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-cleansing-cream.png",
    "summary": "천지향 클렌징 크림은 한방 성분이 메이크업과 노폐물을 부드럽게 용해하여 깨끗하게 씻어냅니다.",
    "description": "천지향 클렌징 크림은 한방 성분이 메이크업과 노폐물을 부드럽게 용해하여 깨끗하게 씻어냅니다. 세정 후에도 피부 당김 없이 촉촉하고 편안한 세정감을 선사합니다.\n\n용량 및 구성: 250ml ㅣ 35,000원\n\n라인: Cheonjiyang Cleansing Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-foam-cleansing",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "십장생 천지향 폼클렌징",
    "price": "32,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-foam-cleansing.png",
    "summary": "천지향 폼클렌징은 부드럽고 풍성한 거품이 모공 속 노폐물과 피지를 깔끔하게 세정합니다.",
    "description": "천지향 폼클렌징은 부드럽고 풍성한 거품이 모공 속 노폐물과 피지를 깔끔하게 세정합니다. 세정 후에도 피부 본연의 수분을 지켜 촉촉하고 산뜻한 사용감을 줍니다.\n\n용량 및 구성: 200ml ㅣ 32,000원\n\n라인: Cheonjiyang Foam Cleansing"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-peeling-gel",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "십장생 천지향 필링겔",
    "price": "36,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-peeling-gel.png",
    "summary": "천지향 필링겔은 한방 성분과 부드러운 각질 케어 성분이 만나 거칠어진 피부결을 매끄럽게 정리합니다.",
    "description": "천지향 필링겔은 한방 성분과 부드러운 각질 케어 성분이 만나 거칠어진 피부결을 매끄럽게 정리합니다. 자극 없이 묵은 각질을 제거하여 피부 흡수력을 높이고 밝은 피부로 가꾸어 줍니다.\n\n용량 및 구성: 150ml ㅣ 36,000원 ㅣ foam cleansing 50ml\n\n라인: Cheonjiyang Peeling Gel"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-sun-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "십장생 천지향 썬크림",
    "price": "40,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-sun-cream.png",
    "summary": "천지향 썬크림은 SPF50+ PA++++의 강력한 자외선 차단력과 함께 한방 보습 성분이 피부를 편안하게 케어합니다.",
    "description": "천지향 썬크림은 SPF50+ PA++++의 강력한 자외선 차단력과 함께 한방 보습 성분이 피부를 편안하게 케어합니다. 산뜻하게 밀착되며 자외선 차단과 스킨케어를 동시에 완성합니다.\n\n용량 및 구성: 80ml ㅣ 40,000원 ㅣ SPF50+ PA++++ / foam cleansing 50ml\n\n라인: Cheonjiyang Sun Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-bb-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "십장생 천지향 비비크림",
    "price": "45,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-bb-cream.png",
    "summary": "천지향 비비크림은 SPF50+ PA++++의 자외선 차단 기능과 자연스러운 피부 커버력을 동시에 제공합니다.",
    "description": "천지향 비비크림은 SPF50+ PA++++의 자외선 차단 기능과 자연스러운 피부 커버력을 동시에 제공합니다. 피부 톤을 균일하게 정돈하며 한방 성분이 피부를 편안하게 가꾸어 줍니다.\n\n용량 및 구성: 50ml ㅣ 45,000원 ㅣ SPF50+ PA++++ / BB cream 10ml\n\n라인: Cheonjiyang BB Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-luminous-essence",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천지향 수분광채 에센스",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-luminous-essence.png",
    "summary": "천지향 수분광채 에센스는 피부 속 깊이 수분을 집중 공급하며 환하고 윤기 있는 피부결을 만들어 줍니다.",
    "description": "천지향 수분광채 에센스는 피부 속 깊이 수분을 집중 공급하며 환하고 윤기 있는 피부결을 만들어 줍니다. 묵직하지 않고 가볍게 흡수되어 하루 종일 생기 있는 광채를 유지시켜 줍니다.\n\n용량 및 구성: 150ml ㅣ 60,000원\n\n라인: Cheonjiyang Moisture Luminous Essence"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-luminous-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천지향 수분광채 크림",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-luminous-cream.png",
    "summary": "천지향 수분광채 크림은 수분과 영양을 풍부하게 담아 피부 표면을 촉촉하고 탄탄하게 마무리합니다.",
    "description": "천지향 수분광채 크림은 수분과 영양을 풍부하게 담아 피부 표면을 촉촉하고 탄탄하게 마무리합니다. 오랜 시간 수분막을 유지하며 건조함 없이 생기 있는 광채 피부를 완성해 줍니다.\n\n용량 및 구성: 150ml ㅣ 60,000원\n\n라인: Cheonjiyang Moisture Luminous Cream"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-2set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 천지향 2종 세트",
    "price": "120,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-2set.png",
    "summary": "천지향 수액과 유액으로 구성된 2종 세트로, 피부 재생과 수분 공급을 동시에 시작할 수 있습니다.",
    "description": "천지향 수액과 유액으로 구성된 2종 세트로, 피부 재생과 수분 공급을 동시에 시작할 수 있습니다. 선물용으로도 손색없는 고품격 한방 스킨케어 세트입니다.\n\n용량 및 구성: 150ml ㅣ 120,000원 ㅣ toner 150ml / emulsion 31ml / cream 15ml\n\n라인: Cheonjiyang 2-Set"
  },
  {
    "slug": "sibjangsaeng-cheonjiyang-3set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 천지향 3종 세트",
    "price": "246,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonjiyang-3set.png",
    "summary": "천지향 수액, 유액, 크림과 앰플까지 구성한 3종 세트로, 천지향 라인의 핵심 제품을 한번에 경험할 수 있습니다.",
    "description": "천지향 수액, 유액, 크림과 앰플까지 구성한 3종 세트로, 천지향 라인의 핵심 제품을 한번에 경험할 수 있습니다. 피부 근본부터 재생, 수분, 마무리까지 완성하는 프리미엄 선물 세트입니다.\n\n용량 및 구성: 150ml ㅣ 246,000원 ㅣ toner, emulsion 150ml, 31ml / cream 50ml / ampoule 30ml\n\n라인: Cheonjiyang 3-Set"
  },
  {
    "slug": "sibjangsaeng-kuman-toner",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 금안수",
    "price": "50,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-toner.png",
    "summary": "금안수는 물 대신 100% '금안수'와 발효십장생복합체를 활용하여 피부 근본부터 다스리는 고품격 한방 수분 베이스입니다.",
    "description": "금안수는 물 대신 100% '금안수'와 발효십장생복합체를 활용하여 피부 근본부터 다스리는 고품격 한방 수분 베이스입니다. 피부 속 깊이 수분을 공급하며 이후 단계의 흡수력을 높여줍니다.\n\n용량 및 구성: 150ml ㅣ 50,000원\n\n라인: Kum-An Skin"
  },
  {
    "slug": "sibjangsaeng-kuman-emulsion",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 금안액",
    "price": "50,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-emulsion.png",
    "summary": "금안액은 100% 금안수와 발효십장생복합체가 피부 깊은 곳까지 수분과 영양을 전달합니다.",
    "description": "금안액은 100% 금안수와 발효십장생복합체가 피부 깊은 곳까지 수분과 영양을 전달합니다. 가볍고 부드럽게 흡수되어 피부 밸런스를 균형 있게 맞추며 하루 종일 촉촉함을 유지시켜 줍니다.\n\n용량 및 구성: 150ml ㅣ 50,000원\n\n라인: Kum-An Emulsion"
  },
  {
    "slug": "sibjangsaeng-kuman-essence",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 금안 진 에센스",
    "price": "85,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-essence.png",
    "summary": "금안 진 에센스는 고농축 금안수와 발효 한방 성분이 피부 속 탄력을 집중적으로 끌어올립니다.",
    "description": "금안 진 에센스는 고농축 금안수와 발효 한방 성분이 피부 속 탄력을 집중적으로 끌어올립니다. 피부 결 깊은 곳부터 생기와 윤기를 채워 건강하고 빛나는 피부로 가꾸어 줍니다.\n\n용량 및 구성: 45ml ㅣ 85,000원 ㅣ toner, emulsion 31ml\n\n라인: Kum-An Jin Essence"
  },
  {
    "slug": "sibjangsaeng-kuman-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 금안 진 크림",
    "price": "90,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-cream.png",
    "summary": "금안 진 크림은 금안수와 발효십장생복합체의 영양이 피부 표면에 보호막을 형성하여 수분 증발을 막아줍니다.",
    "description": "금안 진 크림은 금안수와 발효십장생복합체의 영양이 피부 표면에 보호막을 형성하여 수분 증발을 막아줍니다. 피부 탄력과 윤기를 높이며 스킨케어의 마지막을 풍성하게 완성해 줍니다.\n\n용량 및 구성: 50ml ㅣ 90,000원 ㅣ toner, emulsion 31ml\n\n라인: Kum-An Jin Cream"
  },
  {
    "slug": "sibjangsaeng-kuman-eye-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 금안 진 아이크림",
    "price": "90,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-eye-cream.png",
    "summary": "금안 진 아이크림은 섬세한 눈가 피부에 금안수와 발효 한방 성분을 집중적으로 전달합니다.",
    "description": "금안 진 아이크림은 섬세한 눈가 피부에 금안수와 발효 한방 성분을 집중적으로 전달합니다. 눈가의 잔주름과 처짐을 개선하고 밝고 탄탄한 눈가로 가꾸어 줍니다.\n\n용량 및 구성: 50ml ㅣ 90,000원 ㅣ toner, emulsion 31ml\n\n라인: Kum-An Jin Eye Cream"
  },
  {
    "slug": "sibjangsaeng-kuman-2set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 금안 2종 세트",
    "price": "100,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-2set.png",
    "summary": "금안수와 금안액으로 구성된 2종 세트로, 피부 근본부터 수분과 영양을 채우는 금안 라인을 간편하게 시작할 수 있습니다.",
    "description": "금안수와 금안액으로 구성된 2종 세트로, 피부 근본부터 수분과 영양을 채우는 금안 라인을 간편하게 시작할 수 있습니다. 선물용으로도 손색없는 고품격 한방 스킨케어 세트입니다.\n\n용량 및 구성: 150ml ㅣ 100,000원 ㅣ toner 150ml, emulsion 31ml\n\n라인: Kum-An 2-Set"
  },
  {
    "slug": "sibjangsaeng-kuman-3set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 금안 3종 세트",
    "price": "190,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-kuman-3set.png",
    "summary": "금안수, 금안액, 금안 진 크림과 에센스까지 구성한 3종 세트로, 금안 라인의 핵심 제품을 한번에 경험할 수 있습니다.",
    "description": "금안수, 금안액, 금안 진 크림과 에센스까지 구성한 3종 세트로, 금안 라인의 핵심 제품을 한번에 경험할 수 있습니다. 피부 근본부터 탄력, 수분, 마무리까지 완성하는 프리미엄 선물 세트입니다.\n\n용량 및 구성: 150ml ㅣ 190,000원 ㅣ toner, emulsion 150ml, 31ml / cream 50ml / essence 10ml\n\n라인: Kum-An 3-Set"
  },
  {
    "slug": "sibjangsaeng-cheonsamjin-stick-ampoule",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천삼진 초보양 스틱 앰플",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsamjin-stick-ampoule.png",
    "summary": "천삼진 초보양 스틱 앰플은 야생 산삼 배양 성분이 고농축으로 담겨 지친 피부에 집중적인 영양과 활력을 공급합니다.",
    "description": "천삼진 초보양 스틱 앰플은 야생 산삼 배양 성분이 고농축으로 담겨 지친 피부에 집중적인 영양과 활력을 공급합니다. 간편한 스틱 타입으로 언제 어디서나 손쉽게 사용할 수 있습니다.\n\n용량 및 구성: 27g ㅣ 60,000원 ㅣ ampoule 10ml\n\n라인: Cheonsamjin Vitalze Stick Ampoule"
  },
  {
    "slug": "sibjangsaeng-cheonsamjin-ampoule",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 천삼진 초보양 앰플",
    "price": "220,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-cheonsamjin-ampoule.png",
    "summary": "천삼진 초보양 앰플은 야생 산삼 배양 성분을 10개입으로 구성하여 집중 케어 기간 동안 매일 피부에 깊은 영양과 활력을 전달합니다.",
    "description": "천삼진 초보양 앰플은 야생 산삼 배양 성분을 10개입으로 구성하여 집중 케어 기간 동안 매일 피부에 깊은 영양과 활력을 전달합니다. 피부 재생과 탄력 개선에 도움을 주는 스페셜 케어 앰플입니다.\n\n용량 및 구성: 10ml ㅣ 220,000원 ㅣ ampoule 10ml × 10EA\n\n라인: Cheonsamjin Vitalze Ampoule"
  },
  {
    "slug": "sibjangsaeng-yegyul-toner",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 예결 수액",
    "price": "39,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-toner.png",
    "summary": "예결 수액은 상황버섯추출물이 피부 속 깊이 스며들어 칙칙하고 거친 피부결을 맑고 깨끗하게 정돈합니다.",
    "description": "예결 수액은 상황버섯추출물이 피부 속 깊이 스며들어 칙칙하고 거친 피부결을 맑고 깨끗하게 정돈합니다. 산뜻한 텍스처로 빠르게 흡수되며 이후 스킨케어 단계의 흡수력을 높여줍니다.\n\n용량 및 구성: 130ml ㅣ 39,000원\n\n라인: Yegyul Toner"
  },
  {
    "slug": "sibjangsaeng-yegyul-emulsion",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "십장생 예결 유액",
    "price": "39,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-emulsion.png",
    "summary": "예결 유액은 상황버섯추출물이 피부 수분 밸런스를 균형 있게 케어합니다.",
    "description": "예결 유액은 상황버섯추출물이 피부 수분 밸런스를 균형 있게 케어합니다. 가볍고 산뜻한 텍스처로 빠르게 흡수되어 끈적임 없이 촉촉하고 청결한 피부결로 가꾸어 줍니다.\n\n용량 및 구성: 130ml ㅣ 39,000원\n\n라인: Yegyul Emulsion"
  },
  {
    "slug": "sibjangsaeng-yegyul-essence",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 예결 진액",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-essence.png",
    "summary": "예결 진액은 상황버섯추출물의 고농축 영양이 피부 깊은 곳까지 침투하여 피부 톤을 환하게 밝히고 탄력을 더해줍니다.",
    "description": "예결 진액은 상황버섯추출물의 고농축 영양이 피부 깊은 곳까지 침투하여 피부 톤을 환하게 밝히고 탄력을 더해줍니다. 피부 본연의 맑고 깨끗한 빛을 끌어올려 줍니다.\n\n용량 및 구성: 60ml ㅣ 55,000원 ㅣ toner, emulsion 30ml\n\n라인: Yegyul Essence"
  },
  {
    "slug": "sibjangsaeng-yegyul-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 예결 크림",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-cream.png",
    "summary": "예결 크림은 상황버섯추출물과 한방 보습 성분이 피부 표면에 촉촉한 보호막을 형성합니다.",
    "description": "예결 크림은 상황버섯추출물과 한방 보습 성분이 피부 표면에 촉촉한 보호막을 형성합니다. 피부 톤을 균일하게 정돈하고 맑고 윤기 있는 피부결로 하루를 마무리해 줍니다.\n\n용량 및 구성: 50ml ㅣ 55,000원 ㅣ toner, emulsion 30ml\n\n라인: Yegyul Cream"
  },
  {
    "slug": "sibjangsaeng-yegyul-eye-cream",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "십장생 예결 아이크림",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-eye-cream.png",
    "summary": "예결 아이크림은 상황버섯추출물이 예민한 눈가 피부에 집중적으로 영양을 전달합니다.",
    "description": "예결 아이크림은 상황버섯추출물이 예민한 눈가 피부에 집중적으로 영양을 전달합니다. 눈가의 잔주름과 어두움을 개선하여 밝고 탄탄한 눈가로 가꾸어 줍니다.\n\n용량 및 구성: 50ml ㅣ 55,000원 ㅣ toner, emulsion 30ml\n\n라인: Yegyul Eye Cream"
  },
  {
    "slug": "sibjangsaeng-yegyul-2set",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "korean-skincare",
    "typeName": "한방 스킨케어",
    "name": "십장생 예결 2종 세트",
    "price": "78,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-yegyul-2set.png",
    "summary": "예결 수액과 유액으로 구성된 2종 세트로, 상황버섯추출물의 한방 기초 케어를 간편하게 시작할 수 있습니다.",
    "description": "예결 수액과 유액으로 구성된 2종 세트로, 상황버섯추출물의 한방 기초 케어를 간편하게 시작할 수 있습니다. 선물용으로도 손색없는 한방 기초 스킨케어 세트입니다.\n\n용량 및 구성: 130ml ㅣ 78,000원 ㅣ toner 130ml / emulsion 30ml\n\n라인: Yegyul 2-Set"
  },
  {
    "slug": "sibjangsaeng-beautiful-line-makeup-base",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "십장생 아름다운 선 메이크업베이스",
    "price": "45,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-beautiful-line-makeup-base.png",
    "summary": "아름다운 선 메이크업베이스는 십장생 복합체와 순금 성분이 피부를 건강하고 윤기나게 표현합니다.",
    "description": "아름다운 선 메이크업베이스는 십장생 복합체와 순금 성분이 피부를 건강하고 윤기나게 표현합니다. 메이크업의 밀착력을 높이며 자외선으로부터 피부를 편안하게 보호합니다.\n\n용량 및 구성: 40ml ㅣ 45,000원 ㅣ SPF30 PA++\n\n라인: Beautiful Line Make-Up Base"
  },
  {
    "slug": "sibjangsaeng-beautiful-line-foundation",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "십장생 아름다운 선 파운데이션",
    "price": "45,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-beautiful-line-foundation.png",
    "summary": "아름다운 선 파운데이션은 십장생 복합체와 순금 성분이 피부를 건강하고 빛나게 표현합니다.",
    "description": "아름다운 선 파운데이션은 십장생 복합체와 순금 성분이 피부를 건강하고 빛나게 표현합니다. 21호(회사한색), 23호(자분한색) 두 가지 컬러로 피부 톤에 맞는 자연스러운 커버를 완성합니다.\n\n용량 및 구성: 40ml ㅣ 45,000원 ㅣ SPF35 PA++\n\n라인: Beautiful Line Foundation"
  },
  {
    "slug": "sibjangsaeng-beautiful-line-two-way-cake",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "십장생 아름다운 선 투웨이케익",
    "price": "60,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-beautiful-line-two-way-cake.png",
    "summary": "아름다운 선 투웨이케익은 십장생 복합체와 순금 성분이 피부에 건강한 광채를 더하며 자외선을 차단합니다.",
    "description": "아름다운 선 투웨이케익은 십장생 복합체와 순금 성분이 피부에 건강한 광채를 더하며 자외선을 차단합니다. 21호(회사한색), 23호(자분한색) 두 가지 컬러로 가볍고 산뜻하게 피부를 마무리해 줍니다.\n\n용량 및 구성: 15g ㅣ 60,000원 ㅣ SPF30 PA+++ / refill 내장\n\n라인: Beautiful Line Two-Way Cake"
  },
  {
    "slug": "sibjangsaeng-beautiful-line-skin-cover",
    "brandId": "sibjangsaeng",
    "brandName": "십장생",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "십장생 아름다운 선 스킨커버",
    "price": "55,000원",
    "image": "/assets/products/brand-homepage/sibjangsaeng-beautiful-line-skin-cover.png",
    "summary": "아름다운 선 스킨커버는 십장생 복합체와 순금 성분이 피부 결점을 자연스럽게 커버하며 건강한 피부 톤을 완성합니다.",
    "description": "아름다운 선 스킨커버는 십장생 복합체와 순금 성분이 피부 결점을 자연스럽게 커버하며 건강한 피부 톤을 완성합니다. 21호(회사한색), 23호(자분한색) 두 가지 컬러로 피부에 가볍게 밀착되어 산뜻하게 마무리해 줍니다.\n\n용량 및 구성: 13g ㅣ 55,000원 ㅣ SPF30 PA++ / refill 내장\n\n라인: Beautiful Line Skin Cover"
  },
  {
    "slug": "eco-aloe-shampoo-new",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어샴푸 NEW",
    "price": "14,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-shampoo-new.png",
    "summary": "기존 에코 알로에 헤어샴푸의 사용감을 이어가면서 750ml 용량으로 정리된 데일리 헤어 샴푸입니다.",
    "description": "기존 에코 알로에 헤어샴푸의 사용감을 이어가면서 750ml 용량으로 정리된 데일리 헤어 샴푸입니다.\n\n용량 및 구성: 750ml\n소비자가: 14,000원"
  },
  {
    "slug": "eco-aloe-conditioner-new",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 컨디셔너 NEW",
    "price": "14,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-conditioner-new.png",
    "summary": "알로에 콘셉트의 촉촉한 사용감으로 샴푸 후 모발을 부드럽게 정돈해주는 750ml 컨디셔너입니다.",
    "description": "알로에 콘셉트의 촉촉한 사용감으로 샴푸 후 모발을 부드럽게 정돈해주는 750ml 컨디셔너입니다.\n\n용량 및 구성: 750ml\n소비자가: 14,000원"
  },
  {
    "slug": "eco-aloe-shampoo",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어샴푸",
    "price": "14,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-shampoo.png",
    "summary": "유기농 알로에 15%와 나노 입자화 공법을 담아 두피를 마일드하게 세정하고 매일 쓰기 좋은 산뜻한 사용감을 전하는 대표 샴푸입니다.",
    "description": "유기농 알로에 15%와 나노 입자화 공법을 담아 두피를 마일드하게 세정하고 매일 쓰기 좋은 산뜻한 사용감을 전하는 대표 샴푸입니다.\n\n용량 및 구성: 760ml\n소비자가: 14,000원"
  },
  {
    "slug": "eco-black-garlic-shampoo",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 흑마늘 헤어샴푸",
    "price": "15,000원",
    "image": "/assets/products/brand-homepage/eco-black-garlic-shampoo.png",
    "summary": "발효·숙성 흑마늘 콘셉트로 두피와 모발에 영양감을 더해 탄력 있고 윤기 있는 모발 케어를 제안합니다.",
    "description": "발효·숙성 흑마늘 콘셉트로 두피와 모발에 영양감을 더해 탄력 있고 윤기 있는 모발 케어를 제안합니다.\n\n용량 및 구성: 760ml\n소비자가: 15,000원"
  },
  {
    "slug": "eco-argan-shampoo",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 아르간 헤어샴푸",
    "price": "15,000원",
    "image": "/assets/products/brand-homepage/eco-argan-shampoo.png",
    "summary": "아르간커넬오일의 풍부한 영양과 수분 공급으로 푸석하고 손상된 모발을 부드럽고 건강하게 가꾸는 집중 케어 샴푸입니다.",
    "description": "아르간커넬오일의 풍부한 영양과 수분 공급으로 푸석하고 손상된 모발을 부드럽고 건강하게 가꾸는 집중 케어 샴푸입니다.\n\n용량 및 구성: 760ml\n소비자가: 15,000원"
  },
  {
    "slug": "eco-ginseng-shampoo",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 진생 리바이탈 헤어샴푸",
    "price": "18,000원",
    "image": "/assets/products/brand-homepage/eco-ginseng-shampoo.png",
    "summary": "인삼 이미지를 담은 리바이탈 라인으로 약하고 손상된 모발에 생기와 영양감을 더하는 프리미엄 헤어 케어 제품입니다.",
    "description": "인삼 이미지를 담은 리바이탈 라인으로 약하고 손상된 모발에 생기와 영양감을 더하는 프리미엄 헤어 케어 제품입니다.\n\n용량 및 구성: 760ml\n소비자가: 18,000원"
  },
  {
    "slug": "eco-aloe-conditioner",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 컨디셔너",
    "price": "14,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-conditioner.png",
    "summary": "에코 알로에 헤어 컨디셔너은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 컨디셔너은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 760ml\n소비자가: 14,000원"
  },
  {
    "slug": "eco-aloe-treatment",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 트리트먼트",
    "price": "14,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-treatment.png",
    "summary": "에코 알로에 헤어 트리트먼트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 트리트먼트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 760ml\n소비자가: 14,000원"
  },
  {
    "slug": "eco-aloe-hair-gel",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어젤",
    "price": "13,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-hair-gel.png",
    "summary": "에코 알로에 헤어젤은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어젤은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 530ml\n소비자가: 13,000원"
  },
  {
    "slug": "eco-aloe-multi-essence",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 멀티에센스",
    "price": "16,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-multi-essence.png",
    "summary": "에코 알로에 헤어 멀티에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 멀티에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 530ml\n소비자가: 16,000원"
  },
  {
    "slug": "eco-aloe-hair-spray",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 스프레이",
    "price": "8,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-hair-spray.png",
    "summary": "에코 알로에 헤어 스프레이은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 스프레이은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 300ml\n소비자가: 8,000원"
  },
  {
    "slug": "eco-aloe-coating-essence",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 코팅 에센스",
    "price": "17,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-coating-essence.png",
    "summary": "에코 알로에 헤어 코팅 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 코팅 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 200ml\n소비자가: 17,000원"
  },
  {
    "slug": "eco-aloe-strong-mist",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 초강력 헤어미스트",
    "price": "10,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-strong-mist.png",
    "summary": "에코 알로에 초강력 헤어미스트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 초강력 헤어미스트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 250ml\n소비자가: 10,000원"
  },
  {
    "slug": "eco-aloe-argan-hair-oil",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 아르간 헤어오일",
    "price": "21,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-argan-hair-oil.png",
    "summary": "에코 알로에 아르간 헤어오일은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 아르간 헤어오일은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 200ml\n소비자가: 21,000원"
  },
  {
    "slug": "eco-aloe-gray-cover-color",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 칼라크림 새치용",
    "price": "11,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-gray-cover-color.png",
    "summary": "에코 알로에 헤어 칼라크림 새치용은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 칼라크림 새치용은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 60ml\n소비자가: 11,000원"
  },
  {
    "slug": "eco-aloe-fashion-color",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어칼라 크림 멋내기용",
    "price": "11,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-fashion-color.png",
    "summary": "에코 알로에 헤어칼라 크림 멋내기용은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어칼라 크림 멋내기용은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 60ml\n소비자가: 11,000원"
  },
  {
    "slug": "eco-aloe-curling-essence",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 헤어 컬링 에센스",
    "price": "10,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-curling-essence.png",
    "summary": "에코 알로에 헤어 컬링 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 헤어 컬링 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 150ml\n소비자가: 10,000원"
  },
  {
    "slug": "eco-aloe-body-cleanser",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 바디 클렌저",
    "price": "16,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-body-cleanser.png",
    "summary": "에코 알로에 바디 클렌저은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 바디 클렌저은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 750ml\n소비자가: 16,000원"
  },
  {
    "slug": "eco-aloe-body-essence",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 알로에 바디 에센스",
    "price": "16,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-body-essence.png",
    "summary": "에코 알로에 바디 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 바디 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 500ml\n소비자가: 16,000원"
  },
  {
    "slug": "eco-rose-body-cleanser",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 로즈 바디 클렌저",
    "price": "16,000원",
    "image": "/assets/products/brand-homepage/eco-rose-body-cleanser.png",
    "summary": "에코 로즈 바디 클렌저은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 로즈 바디 클렌저은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 760ml\n소비자가: 16,000원"
  },
  {
    "slug": "eco-rose-body-essence",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 로즈 바디 에센스",
    "price": "16,000원",
    "image": "/assets/products/brand-homepage/eco-rose-body-essence.png",
    "summary": "에코 로즈 바디 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 로즈 바디 에센스은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 530ml\n소비자가: 16,000원"
  },
  {
    "slug": "eco-lime-mint-body-set",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "에코 라임민트 바디 2종세트",
    "price": "38,000원",
    "image": "/assets/products/brand-homepage/eco-lime-mint-body-set.png",
    "summary": "에코 라임민트 바디 2종세트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 라임민트 바디 2종세트은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 세트구성\n소비자가: 38,000원"
  },
  {
    "slug": "eco-aloe-moisture-cleansing-foam",
    "brandId": "eco-aloe",
    "brandName": "에코알로에",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "에코 알로에 모이스처 클렌징폼",
    "price": "15,000원",
    "image": "/assets/products/brand-homepage/eco-aloe-moisture-cleansing-foam.jpg",
    "summary": "에코 알로에 모이스처 클렌징폼은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.",
    "description": "에코 알로에 모이스처 클렌징폼은 에코알로에 브랜드 홈페이지 자료를 기준으로 등록한 데일리 케어 제품입니다.\n\n용량 및 구성: 200ml\n소비자가: 15,000원"
  },
  {
    "slug": "majarin-sunblock",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "마자린 마린콜라겐 선블럭",
    "price": "22,000원",
    "image": "/assets/products/majarin-sunblock.png",
    "summary": "마자린의 마스크/마사지/SUN 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 선블럭은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 마스크/마사지/SUN 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 22,000원입니다."
  },
  {
    "slug": "majarin-2",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "마자린 마린콜라겐 플러스 2종세트",
    "price": "44,000원",
    "image": "/assets/products/majarin-2.png",
    "summary": "마자린의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 2종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 44,000원입니다."
  },
  {
    "slug": "majarin-3",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "마자린 마린콜라겐 플러스 3종세트",
    "price": "44,000원",
    "image": "/assets/products/majarin-3.png",
    "summary": "마자린의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 3종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 44,000원입니다."
  },
  {
    "slug": "majarin",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "마자린 마린콜라겐 플러스 스킨",
    "price": "22,000원",
    "image": "/assets/products/majarin.png",
    "summary": "마자린의 토너&로션 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 스킨은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 토너&로션 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 22,000원입니다."
  },
  {
    "slug": "majarin-4",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "마자린 마린콜라겐 플러스 에멀전",
    "price": "22,000원",
    "image": "/assets/products/majarin-4.png",
    "summary": "마자린의 토너&로션 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 에멀전은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 토너&로션 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 22,000원입니다."
  },
  {
    "slug": "majarin-essence",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "마자린 마린콜라겐 플러스 에센스",
    "price": "25,000원",
    "image": "/assets/products/majarin-essence.png",
    "summary": "마자린의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 에센스은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 25,000원입니다."
  },
  {
    "slug": "majarin-cream",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "마자린 마린콜라겐 플러스 크림",
    "price": "25,000원",
    "image": "/assets/products/majarin-cream.png",
    "summary": "마자린의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "마자린 마린콜라겐 플러스 크림은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 25,000원입니다."
  },
  {
    "slug": "majarin-cream-2",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "마자린 스네일 수분크림",
    "price": "25,000원",
    "image": "/assets/products/majarin-cream-2.jpg",
    "summary": "마자린의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "마자린 스네일 수분크림은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 25,000원입니다."
  },
  {
    "slug": "majarin-cleansing",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "마자린 캐비어 클렌징폼",
    "price": "12,000원",
    "image": "/assets/products/majarin-cleansing.png",
    "summary": "마자린의 클렌징 카테고리 제품입니다.",
    "description": "마자린 캐비어 클렌징폼은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 클렌징 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 12,000원입니다."
  },
  {
    "slug": "majarin-spf30pa",
    "brandId": "majarin",
    "brandName": "마자린",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "마자린 콜라겐 비비spf30pa+",
    "price": "19,000원",
    "image": "/assets/products/majarin-spf30pa.png",
    "summary": "마자린의 메이크업 카테고리 제품입니다.",
    "description": "마자린 콜라겐 비비spf30pa+은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 마자린 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 19,000원입니다."
  },
  {
    "slug": "opus-2-2",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "오퍼스 로맨틱 루비어스 2종세트",
    "price": "56,000원",
    "image": "/assets/products/opus-2-2.png",
    "summary": "오퍼스의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 루비어스 2종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 56,000원입니다."
  },
  {
    "slug": "opus",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "오퍼스 로맨틱 루비어스 스킨",
    "price": "28,000원",
    "image": "/assets/products/opus.png",
    "summary": "오퍼스의 토너&로션 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 루비어스 스킨은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 토너&로션 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 28,000원입니다."
  },
  {
    "slug": "opus-4",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "toner-lotion",
    "typeName": "토너&로션",
    "name": "오퍼스 로맨틱 루비어스 에멀전",
    "price": "28,000원",
    "image": "/assets/products/opus-4.png",
    "summary": "오퍼스의 토너&로션 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 루비어스 에멀전은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 토너&로션 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 28,000원입니다."
  },
  {
    "slug": "opus-essence",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "오퍼스 로맨틱 루비어스 에센스",
    "price": "34,000원",
    "image": "/assets/products/opus-essence.png",
    "summary": "오퍼스의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 루비어스 에센스은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 34,000원입니다."
  },
  {
    "slug": "opus-cream",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "오퍼스 로맨틱 루비어스 크림",
    "price": "34,000원",
    "image": "/assets/products/opus-cream.png",
    "summary": "오퍼스의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 루비어스 크림은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 34,000원입니다."
  },
  {
    "slug": "opus-sun-cream",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "sun-mask",
    "typeName": "마스크/마사지/SUN",
    "name": "오퍼스 로맨틱 선크림",
    "price": "22,000원",
    "image": "/assets/products/opus-sun-cream.png",
    "summary": "오퍼스의 마스크/마사지/SUN 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 선크림은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 마스크/마사지/SUN 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 22,000원입니다."
  },
  {
    "slug": "opus-5",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "오퍼스 로맨틱 필링젤(리뉴얼)",
    "price": "26,000원",
    "image": "/assets/products/opus-5.png",
    "summary": "오퍼스의 헤어&바디 카테고리 제품입니다.",
    "description": "오퍼스 로맨틱 필링젤(리뉴얼)은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 헤어&바디 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 26,000원입니다."
  },
  {
    "slug": "opus-2-3",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "men",
    "typeName": "남성제품",
    "name": "오퍼스 옴므 2종세트",
    "price": "38,000원",
    "image": "/assets/products/opus-2-3.jpg",
    "summary": "오퍼스의 남성제품 카테고리 제품입니다.",
    "description": "오퍼스 옴므 2종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 남성제품 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 38,000원입니다."
  },
  {
    "slug": "opus-2-4",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "men",
    "typeName": "남성제품",
    "name": "오퍼스 옴므 알로에 2종세트",
    "price": "38,000원",
    "image": "/assets/products/opus-2-4.png",
    "summary": "오퍼스의 남성제품 카테고리 제품입니다.",
    "description": "오퍼스 옴므 알로에 2종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 남성제품 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 38,000원입니다."
  },
  {
    "slug": "opus-essence-2",
    "brandId": "opus",
    "brandName": "오퍼스",
    "typeId": "men",
    "typeName": "남성제품",
    "name": "오퍼스 옴므 올인원 스킨에센스",
    "price": "28,000원",
    "image": "/assets/products/opus-essence-2.png",
    "summary": "오퍼스의 남성제품 카테고리 제품입니다.",
    "description": "오퍼스 옴므 올인원 스킨에센스은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 오퍼스 라인의 남성제품 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 28,000원입니다."
  },
  {
    "slug": "rosee-blossom-makeup-base",
    "brandId": "blossom",
    "brandName": "로제블라썸",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "로제 블라썸 메이크업베이스",
    "price": "24,000원",
    "image": "/assets/products/rosee-blossom-makeup-base.png",
    "summary": "로제블라썸의 메이크업 카테고리 제품입니다.",
    "description": "로제 블라썸 메이크업베이스은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 로제블라썸 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 24,000원입니다."
  },
  {
    "slug": "rosee-blossom-skin-cover21-23",
    "brandId": "blossom",
    "brandName": "로제블라썸",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "로제 블라썸 스킨커버21,23호",
    "price": "34,000원",
    "image": "/assets/products/rosee-blossom-skin-cover21-23.png",
    "summary": "로제블라썸의 메이크업 카테고리 제품입니다.",
    "description": "로제 블라썸 스킨커버21,23호은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 로제블라썸 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 34,000원입니다."
  },
  {
    "slug": "rosee-blossom-cushion21-23",
    "brandId": "blossom",
    "brandName": "로제블라썸",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "로제 블라썸 쿠션21,23호",
    "price": "38,000원",
    "image": "/assets/products/rosee-blossom-cushion21-23.png",
    "summary": "로제블라썸의 메이크업 카테고리 제품입니다.",
    "description": "로제 블라썸 쿠션21,23호은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 로제블라썸 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 38,000원입니다."
  },
  {
    "slug": "rosee-blossom-twoway-cake-21-23",
    "brandId": "blossom",
    "brandName": "로제블라썸",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "로제 블라썸 투웨이케익 21,23호",
    "price": "32,000원",
    "image": "/assets/products/rosee-blossom-twoway-cake-21-23.png",
    "summary": "로제블라썸의 메이크업 카테고리 제품입니다.",
    "description": "로제 블라썸 투웨이케익 21,23호은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 로제블라썸 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 32,000원입니다."
  },
  {
    "slug": "rosee-blossom-foundation21-23",
    "brandId": "blossom",
    "brandName": "로제블라썸",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "로제 블라썸 파운데이션21,23호",
    "price": "24,000원",
    "image": "/assets/products/rosee-blossom-foundation21-23.png",
    "summary": "로제블라썸의 메이크업 카테고리 제품입니다.",
    "description": "로제 블라썸 파운데이션21,23호은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 로제블라썸 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 24,000원입니다."
  },
  {
    "slug": "celactive",
    "brandId": "celactive",
    "brandName": "셀액티브",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "셀액티브 마스카라",
    "price": "18,000원",
    "image": "/assets/products/celactive.jpg",
    "summary": "셀액티브의 메이크업 카테고리 제품입니다.",
    "description": "셀액티브 마스카라은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 셀액티브 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 18,000원입니다."
  },
  {
    "slug": "celactive-2",
    "brandId": "celactive",
    "brandName": "셀액티브",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "셀액티브 아이라이너",
    "price": "17,000원",
    "image": "/assets/products/celactive-2.png",
    "summary": "셀액티브의 메이크업 카테고리 제품입니다.",
    "description": "셀액티브 아이라이너은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 셀액티브 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 17,000원입니다."
  },
  {
    "slug": "eve-doctor-ewg-cleansing",
    "brandId": "eve-doctor",
    "brandName": "이브닥터",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "이브닥터 제떼 EWG그린 저자극 약산성 클렌징 버블폼",
    "price": "13,000원",
    "image": "/assets/products/eve-doctor-ewg-cleansing.png",
    "summary": "이브닥터의 클렌징 카테고리 제품입니다.",
    "description": "이브닥터 제떼 EWG그린 저자극 약산성 클렌징 버블폼은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 이브닥터 라인의 클렌징 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 13,000원입니다."
  },
  {
    "slug": "eve-doctor-ewg-cleansing-2",
    "brandId": "eve-doctor",
    "brandName": "이브닥터",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "이브닥터 제떼 EWG그린 저자극 약산성 클렌징 워터",
    "price": "13,000원",
    "image": "/assets/products/eve-doctor-ewg-cleansing-2.png",
    "summary": "이브닥터의 클렌징 카테고리 제품입니다.",
    "description": "이브닥터 제떼 EWG그린 저자극 약산성 클렌징 워터은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 이브닥터 라인의 클렌징 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 13,000원입니다."
  },
  {
    "slug": "eve-doctor-cleansing",
    "brandId": "eve-doctor",
    "brandName": "이브닥터",
    "typeId": "cleansing",
    "typeName": "클렌징",
    "name": "이브닥터 제떼 클렌징 젤 폼",
    "price": "13,000원",
    "image": "/assets/products/eve-doctor-cleansing.png",
    "summary": "이브닥터의 클렌징 카테고리 제품입니다.",
    "description": "이브닥터 제떼 클렌징 젤 폼은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 이브닥터 라인의 클렌징 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 13,000원입니다."
  },
  {
    "slug": "eve-doctor-hair-shampoo",
    "brandId": "eve-doctor",
    "brandName": "이브닥터",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "이브닥터 헤어로스 케어 샴푸",
    "price": "20,000원",
    "image": "/assets/products/eve-doctor-hair-shampoo.png",
    "summary": "이브닥터의 헤어&바디 카테고리 제품입니다.",
    "description": "이브닥터 헤어로스 케어 샴푸은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 이브닥터 라인의 헤어&바디 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 20,000원입니다."
  },
  {
    "slug": "eve-doctor-hair",
    "brandId": "eve-doctor",
    "brandName": "이브닥터",
    "typeId": "hair-body",
    "typeName": "헤어&바디",
    "name": "이브닥터 헤어로스케어 토닉",
    "price": "20,000원",
    "image": "/assets/products/eve-doctor-hair.png",
    "summary": "이브닥터의 헤어&바디 카테고리 제품입니다.",
    "description": "이브닥터 헤어로스케어 토닉은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 이브닥터 라인의 헤어&바디 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 20,000원입니다."
  },
  {
    "slug": "rosee-formen-2",
    "brandId": "misc-items",
    "brandName": "기타품목",
    "typeId": "men",
    "typeName": "남성제품",
    "name": "로제 포맨 2종세트",
    "price": "30,000원",
    "image": "/assets/products/rosee-formen-2.png",
    "summary": "스페셜 라인의 남성제품 카테고리 제품입니다.",
    "description": "로제 포맨 2종세트은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 스페셜 라인 라인의 남성제품 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 30,000원입니다."
  },
  {
    "slug": "rosee",
    "brandId": "misc-items",
    "brandName": "기타품목",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "로제 핑크 멀티밤",
    "price": "28,000원",
    "image": "/assets/products/rosee.jpg",
    "summary": "스페셜 라인의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "로제 핑크 멀티밤은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 스페셜 라인 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 28,000원입니다."
  },
  {
    "slug": "cyserea-cream2",
    "brandId": "cyserea",
    "brandName": "시세리아",
    "typeId": "cream-essence",
    "typeName": "크림&에센스&앰플",
    "name": "시세리아 핸드크림2종",
    "price": "9,000원",
    "image": "/assets/products/cyserea-cream2.png",
    "summary": "스페셜 라인의 크림&에센스&앰플 카테고리 제품입니다.",
    "description": "시세리아 핸드크림2종은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 스페셜 라인 라인의 크림&에센스&앰플 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다. 소비자가 기준가는 9,000원입니다."
  },
  {
    "slug": "cyserea-perfume",
    "brandId": "cyserea",
    "brandName": "시세리아",
    "typeId": "fragrance",
    "typeName": "향수&기타",
    "name": "시세리아 향수",
    "price": "소비자가 문의",
    "image": "/assets/products/cyserea-perfume.png",
    "summary": "스페셜 라인의 향수&기타 카테고리 제품입니다.",
    "description": "시세리아 향수은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 스페셜 라인 라인의 향수&기타 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다."
  },
  {
    "slug": "uv-twoway-cake",
    "brandId": "misc-items",
    "brandName": "기타품목",
    "typeId": "makeup",
    "typeName": "메이크업",
    "name": "환희 UV 투웨이케익",
    "price": "소비자가 문의",
    "image": "/assets/products/uv-twoway-cake.png",
    "summary": "스페셜 라인의 메이크업 카테고리 제품입니다.",
    "description": "환희 UV 투웨이케익은 로제화장품 카탈로그 자료와 제품 이미지 폴더를 기준으로 등록한 스페셜 라인 라인의 메이크업 제품입니다. 제품 상세 설명과 전성분, 용량 정보는 추후 공식 자료에 맞춰 추가 보완할 수 있습니다."
  }
] as const;
